### ISSUE TITLE
Find all places which can / should be debuggable

### ISSUE THREAD

**Issue by lunetics** [prooph/service-bus-symfony-bundle#17]
What do you guys should be good information on the toolbar? Just throw all ideas in here.

So far i would propose one tool bar for each bus : Command, Event and Query bus

Command and Event bus should show all called handlers?

The query bus could additionally implement some interface for debugging for "raw" data (query / response using symfony vardumper)

**Comment by prolic** [comment]
No additional interface, just a plugin I think.

Am 29.03.2017 07:18 schrieb "Matthias Breddin" <notifications@github.com>:

**Comment by mablae** [comment]
@lunetics I like the idea and the screenshots you posted. Just make a WIP Branch from it to discucss further?
