### ISSUE TITLE
ProophServiceBusExtension forces you to use more symfony components then you need.

### ISSUE THREAD

**Issue by lchrusciel** [prooph/service-bus-symfony-bundle#44]
If command bus is used in test environment `ProophServiceBusExtension` adds `DataCollectorPlugin` even if you don't have required components(as `StopWatch` for example). It is problematic especially when one tries to use symfony flex and build an app with the lowest amount of dependencies as possible. 

Should the `StopWatch` be added as a hard dependency to composer.json? Or do you have better idea how should it be handled?

**Comment by UFOMelkor** [comment]
You're right, we disabled the StopwatchPlugin but missed the DataCollectorPlugin.

StopWatch should stay an optional dependency.
