### ISSUE TITLE
 The "message" tag key is missing from tag. Either provide a "message" tag or enable "message_detection" for service 

### ISSUE THREAD

**Issue by xgc1986** [prooph/service-bus-symfony-bundle#53]
I've been following the documentation, and when I execute I received the following message
` The "message" tag key is missing from tag. Either provide a "message" tag or enable "message_detection" for service `

using Symfony 4

**Comment by UFOMelkor** [comment]
Hey @xgc1986,

Can you share your message configuration?

**Comment by xgc1986** [comment]
I found the issue, I had to add the tag message with the Query class name as the value. In the documentation does not say anything of this message or which value it has to have, later I will create a pull request with this correction.
