### ISSUE TITLE
Make handlers public by default

### ISSUE THREAD

**Issue by UFOMelkor** [prooph/service-bus-symfony-bundle#56]
I could not recognize a scenario where a private handler is needed. Therefore we could make handlers automatically public.

**Comment by enumag** [comment]
The best practice in symfony to have all services private unless there is a reason to make it public. So the correct question is whether or not there is a scenario to have handlers public.

**Comment by UFOMelkor** [comment]
That's correct, but AFAIK private services cannot be fetched from the container and that's happening in the [ServiceLocatorPlugin](https://github.com/prooph/service-bus/blob/a9b0a7e9d9ffb35cd7a716a552e543be177e171f/src/Plugin/ServiceLocatorPlugin.php#L45).

**Comment by enumag** [comment]
Indeed that's a valid scenario. They should be public then.

**Comment by UFOMelkor** [comment]
While #57 forced handlers to be public that are configured using tags, handlers that are added to routes are not forced. Will provide a PR for this tomorrow.

**Comment by UFOMelkor** [comment]
Link https://github.com/prooph/service-bus-symfony-bundle/pull/60#issuecomment-358616904
