### ISSUE TITLE
automatic routing for query bus?

### ISSUE THREAD

**Issue by n3vrax** [prooph/service-bus-symfony-bundle#72]
Just wanted to ask if this is supported, as described for the command bus.
Tried to setup the query bus as per command bus analogy, but I cannot make it work

#### services.yaml
```
App\Application\QueryHandler\:
        resource: '../src/Application/QueryHandler/*Handler.php'
        tags: [{name: 'prooph_service_bus.default_querybus.route_target', message_detection: true}]
```

**Comment by n3vrax** [comment]
Ok, probably my bad, it looks like the "magic" does not work with plain query objects. Extending the Query class seems to do the job. Is this related to the internal messageName?

**Comment by UFOMelkor** [comment]
Yes, message detection currently works only if the message implements `Prooph\Common\Messaging\HasMessageName`.

I plan to add support for POPOs by using the FQCN as fallback.
