### ISSUE TITLE
Symfony 4  QueryBus was not able to identify a Finder for query "path to query" at /app/vendor/prooph/service-bus/src/QueryBus.php:56

### ISSUE THREAD

**Issue by kamil-nawrotkiewicz** [prooph/service-bus-symfony-bundle#76]
After change version symfony from 3.4 to 4.2 i have problem with implementation queryBus in my project. I get response: QueryBus was not able to identify a Finder for query "path" at /app/vendor/prooph/service-bus/src/QueryBus.php:56. It looks like the query does not see the handler. I tried make it with file config prooph_service_bus.php, but still not work. You could help solve this problem?

**Comment by kamil-nawrotkiewicz** [comment]
Problem solved in services.yaml it was enough to add: 
Prooph\Bundle\ServiceBus\QueryBus: '@prooph_service_bus.main_query_bus'

**Comment by gquemener** [comment]
Helllo,

This issue should be closed if it's been resolved.

What's your status @kamil-nawrotkiewicz ?
